axon:
  serializer:
    general: jackson
  eventhandling:
    processors:
      "[MyProcessor]":
        source: kafkaMessageSource
        mode: TRACKING
        threadCount: 1
        batchSize: 1
  kafka:
    clientid: myconsumer
    defaulttopic: mydefaulttopic
    consumer:
      group-id: boot
      bootstrapservers:
        - kafka:9092

logging:
  level:
    ROOT: INFO